In [13]:
# Library
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn.linear_model

In [15]:
# Load Data
oecd_bli = pd.read_csv('Data/oecd.csv.csv', thousands=",")
gdp_per_capita = pd.read_csv('Data/gdp_per_capita.csv', thousands=",", delimiter='\t', encoding='latin1', na_values="n/a")

ParserError: Error tokenizing data. C error: Expected 3 fields in line 3, saw 4

In [9]:
oecd_bli.head()

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,AUS,Australia,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,5.4,NaN,NaN
1,AUT,Austria,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.5,NaN,NaN
2,BEL,Belgium,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.7,NaN,NaN
3,CAN,Canada,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,6.0,NaN,NaN
4,CZE,Czech Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.1,NaN,NaN

In [10]:
gdp_per_capita.head()

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2018,2019,2020,2021,2022,2023,2024,2025,2026,"Estimates Start After,,,,,,,,,,,,,,,,,,"
0,"512\tAFG\tNGDP_R\tAfghanistan\t""Gross domestic...",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,NaN,NaN,NaN,NaN,...,"1"",""363.06""""","1"",""424.40""""","1"",""481.50""""","1"",""540.94""""","1"",""602.59""""","2019""",NaN,NaN,NaN,NaN
1,"512\tAFG\tNGDP_RPCH\tAfghanistan\t""Gross domes...",Annual percentages of constant price GDP are y...,Percent change,NaN,"See notes for: Gross domestic product"","" cons...",NaN,NaN,NaN,NaN,NaN,...,4.524,4.5,4.009,4.012,4.001,"2019"",,,,,,,,,,,,,,,",NaN,NaN,NaN,NaN
2,"512\tAFG\tNGDP\tAfghanistan\t""Gross domestic p...",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,NaN,NaN,NaN,NaN,...,"1"",""745.26""""","1"",""896.29""""","2"",""051.19""""","2"",""218.82""""","2"",""399.92""""","2019""",NaN,NaN,NaN,NaN
3,"512\tAFG\tNGDPD\tAfghanistan\t""Gross domestic ...",Values are based upon GDP in national currency...,U.S. dollars,Billions,"See notes for: Gross domestic product"","" curr...",NaN,NaN,NaN,NaN,NaN,...,21.201,22.01,22.754,23.896,24.553,"2019"",,,,,,,,,,,,,,,",NaN,NaN,NaN,NaN
4,"512\tAFG\tPPPGDP\tAfghanistan\t""Gross domestic...",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,NaN,NaN,NaN,NaN,...,89.114,95.23,101.121,107.246,113.629,2019,NaN,NaN,NaN,NaN